"""Static download endpoint for the roster-codebase bundle.

A one-off endpoint that lets the user download the pre-generated bundle
without giving them shell access. The tarball is generated by the agent
when the user asks for it and dropped into `/app/exports/`.
"""
from __future__ import annotations

import os
from pathlib import Path

from fastapi import HTTPException
from fastapi.responses import FileResponse

from database import api_router, ROOT_DIR


# `/app/backend` → `/app` → `/app/exports`
_EXPORT_DIR = Path(ROOT_DIR).parent / "exports"


@api_router.get("/exports/{filename}")
def download_export(filename: str):
    """Serve a generated bundle from /app/exports.

    Only allows whitelisted filenames so this endpoint can't be abused as
    an arbitrary file-read. Public (no auth) — the bundle contains code
    that's also visible in the user's GitHub mirror.
    """
    allowed = {
        "roster_bundle.tar.gz",
        "roster_bundle.zip",
    }
    if filename not in allowed:
        raise HTTPException(status_code=404, detail="Not found")

    path = _EXPORT_DIR / filename
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Bundle {filename} not generated yet.",
        )

    return FileResponse(
        path=str(path),
        filename=filename,
        media_type=(
            "application/gzip" if filename.endswith(".tar.gz")
            else "application/zip"
        ),
    )
